name:                symtegration
version:             0.6.1
homepage:            https://symtegration.dev/
github:              "symtegration/symtegration"
author:              "Yoo Chung"
maintainer:          "dev@chungyc.org"
copyright:           Copyright 2025 Yoo Chung
license:             Apache-2.0

extra-source-files:
- LICENSE
- README.md
- docs/**

synopsis:            Library for symbolic integration of mathematical expressions.
category:            Mathematics, Symbolic Computation

description: |
  Symtegration is a library providing symbolic integration of mathematical expressions.
  .
  For example,
  .
  >>> import Symtegration
  >>> toHaskell <$> integrate "x" (4 * "x" ** 3 + 1)
  Just "x + x ** 4"
  .
  See the "Symtegration" module for the main interface.

tested-with: GHC == 9.12.1 || == 9.10.1 || == 9.8.4 || == 9.6.6

language: GHC2021

default-extensions:
- LambdaCase
- OverloadedStrings

ghc-options:
- -Wall

dependencies:
- ad >= 4.5 && < 4.6
- base >= 4.18 && < 4.22
- containers >= 0.6 && < 0.8
- text >= 2.0 && < 2.2
- text-show >= 3.10 && < 3.12

library:
  source-dirs: src

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - symtegration
    - hspec >= 2.11 && < 2.12
    - QuickCheck >= 2.14 && < 2.16
    build-tools:
    - hspec-discover >= 2.11 && < 2.12

    when:
      condition: false
      other-modules:
      - Examples  # Don't include the doctest runner.

  examples:
    main:                test/Examples.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - symtegration
    - doctest-parallel >= 0.3 && < 0.4
