name:                symtegration
version:             0.3.0
homepage:            https://symtegration.dev/
github:              "symtegration/symtegration"
author:              "Yoo Chung"
maintainer:          "dev@chungyc.org"
copyright:           Copyright 2025 Yoo Chung
license:             Apache-2.0

extra-source-files:
- LICENSE
- README.md
- docs/**

synopsis:            Library for symbolic integration of mathematical expressions.
category:            Mathematics, Symbolic Computation

description: |
  Symtegration is a library providing symbolic integration of mathematical expressions.
  See the [README](https://github.com/symtegration/symtegration#readme) on GitHub.

language: GHC2021

default-extensions:
- LambdaCase
- OverloadedStrings

ghc-options:
- -Wall
- -Werror

dependencies:
- ad >= 4.5 && < 4.6
- base >= 4.18 && < 4.21
- containers >= 0.6 && < 0.8
- text >= 2.0 && < 2.2
- text-show >= 3.10 && < 3.11

library:
  source-dirs: src

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - symtegration
    - containers >= 0.6 && < 0.8
    - hspec >= 2.11 && < 2.12
    - QuickCheck >= 2.14 && < 2.15
    build-tool-depends:
    - hspec-discover >= 2.11 && < 2.12

    when:
      condition: false
      other-modules:
      - Examples  # Don't include the doctest runner.

  examples:
    main:                test/Examples.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - symtegration
    - containers >= 0.6 && < 0.8
    - doctest-parallel >= 0.3 && < 0.4
