# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# A 'specific' Stackage snapshot or a compiler version.
snapshot: lts-23.1

# User packages to be built.
packages:
- .
