blank_issues_enabled: false
contact_links:
  - name: Discuss ideas or ask questions
    url: https://github.com/symtegration/symtegration/discussions
    about: Please ask and answer questions in discussions
