name: Build
permissions: read-all

on:
  push:
    branches:
      - 'main'

  pull_request:
    paths:
      - 'stack.yaml'
      - 'package.yaml'
      - 'symtegration.cabal'
      - '**.hs'
      - '.github/workflows/build.yaml'

jobs:
  cabal:
    strategy:
      matrix:
        os:
          - "ubuntu-24.04-arm"

        # Policy for compatible GHC versions is to:
        # * Test three most recent minor versions.
        # * Test lowest and highest minor versions of the current and previous major versions.
        # * Test highest minor version of major versions before the second last.
        ghc:
          - "9.6.6"
          - "9.8.4"
          - "9.10.1"
          - "9.12.1"

      fail-fast: false

    name: cabal / ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Cache dependencies
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            ~/.cabal
            ~/.ghcup
          key: cabal-${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('symtegration.cabal') }}
          restore-keys: cabal-${{ matrix.os }}-${{ matrix.ghc }}-

      - name: Setup Haskell
        uses: haskell-actions/setup@7909071ceec0344debcc968c6c7a96a52e8dd0d7 # v2.8.1
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Build
        run: |
          cabal configure --enable-optimization --enable-tests --write-ghc-environment-files=always --ghc-options="-Wall -Werror"
          cabal build

      - name: Test
        run: cabal run spec
        timeout-minutes: 10

      - name: Test examples
        run: cabal run examples

  stack:
    name: stack
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Cache dependencies
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: |
            ~/.ghcup
            ~/.stack
          key: stack-${{ hashFiles('stack.yaml', 'package.yaml') }}
          restore-keys: stack-

      - name: Setup Haskell
        uses: haskell-actions/setup@7909071ceec0344debcc968c6c7a96a52e8dd0d7 # v2.8.1
        with:
          enable-stack: true

      - name: Build
        run: stack build --pedantic --coverage --test --no-run-tests

      - name: Test
        run: stack build --pedantic --coverage --test
        timeout-minutes: 10

      - name: Generate coverage report
        uses: 8c6794b6/hpc-codecov-action@99cd60d788cb04eeba9da1550a7c753ec44f2c66 # v4.2.0
        with:
          target: stack:spec

      - name: Upload coverage report
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
