name: Build
permissions: read-all

on:
  push:
    branches:
      - 'main'

  pull_request:
    paths:
      - 'stack.yaml'
      - 'package.yaml'
      - 'symtegration.cabal'
      - '**.hs'
      - '.github/workflows/build.yaml'

jobs:
  cabal:
    strategy:
      matrix:
        os:
          - "ubuntu-24.04-arm"

        # Policy for compatible GHC versions is to:
        # * Test three most recent minor versions.
        # * Test lowest and highest minor versions of the current and previous major versions.
        # * Test highest minor version of major versions before the second last.
        ghc:
          - "9.6.6"
          - "9.8.4"
          - "9.10.1"
          - "9.12.1"

      fail-fast: false

    name: cabal / ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache dependencies
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: |
            ~/.cabal
            ~/.ghcup
          key: cabal-${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('symtegration.cabal') }}
          restore-keys: cabal-${{ matrix.os }}-${{ matrix.ghc }}-

      - name: Setup Haskell
        uses: haskell-actions/setup@bbd90a29996ac33b1c644a42206e312fc0379748 # v2.7.9
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Build
        run: |
          cabal configure --enable-optimization --enable-tests --write-ghc-environment-files=always --ghc-options="-Wall -Werror"
          cabal build

      - name: Test
        run: cabal run spec
        timeout-minutes: 10

      - name: Test examples
        run: cabal run examples

  stack:
    name: stack
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache dependencies
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: |
            ~/.ghcup
            ~/.stack
          key: stack-${{ hashFiles('stack.yaml', 'package.yaml') }}
          restore-keys: stack-

      - name: Setup Haskell
        uses: haskell-actions/setup@bbd90a29996ac33b1c644a42206e312fc0379748 # v2.7.9
        with:
          enable-stack: true

      - name: Build
        run: stack build --pedantic --coverage --test --no-run-tests

      - name: Test
        run: stack build --pedantic --coverage --test
        timeout-minutes: 10

      - name: Generate coverage report
        uses: 8c6794b6/hpc-codecov-action@0baa5bacbd3ed4103ca4e25495e6e9cf0469912b # v4.1.0
        with:
          target: stack:spec

      - name: Upload coverage report
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
