name: Ormolu
permissions: read-all

on:
  push:
    branches:
      - 'main'

  pull_request:
    paths:
      - '**.hs'
      - '.github/workflows/ormolu.yaml'

jobs:
  ormolu:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: haskell-actions/run-ormolu@ca5937ef20713809e10da8f470956218014f8e96 # v20
